# Numpy

In [1]:
import numpy as np

## Numpy Array

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a[0]

np.int64(1)

In [6]:
a[-1]

np.int64(4)

In [7]:
a[0:2]

array([1, 2])

In [8]:
a.shape

(4,)

In [9]:
a.ndim

1

In [10]:
a.size

4

In [12]:
a.dtype  # int64: 8B, Python Int: 28B

dtype('int64')

Datentypen:
- int8
- int16
- int32
- int64

- float16
- float32
- float64

In [13]:
b = np.array([1, 2, 3, 4], dtype=np.int8)

In [14]:
b

array([1, 2, 3, 4], dtype=int8)

## Matrizen

In [15]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
c[0]

array([1, 2, 3])

In [18]:
c[-1]

array([7, 8, 9])

In [19]:
c[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
c[0][1]

np.int64(2)

In [22]:
c[0, 1]  # In Python nicht möglich

np.int64(2)

In [23]:
c[0:3, -1]

array([3, 6, 9])

In [25]:
c[:, -1]  # Alle Zeilen, letzte Spalte

array([3, 6, 9])

In [26]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
c[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [31]:
c.sum()

np.int64(45)

In [32]:
c[0].sum()

np.int64(6)

In [35]:
c[:, 1].sum()

np.int64(15)

In [37]:
c.sum(axis=0)  # Senkrechte Summen berechnen

array([12, 15, 18])

In [38]:
c.sum(axis=1)

array([ 6, 15, 24])

## Vektorisierung

In [42]:
d = np.array(range(10))

In [43]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
d + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
d * d  # Die beiden Arrays müssen die gleiche Größe haben

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

## Boolean Masken

In [47]:
d > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [49]:
bedingung = d > 5

In [50]:
d[bedingung]  # Boolean Maske auf das Array zurückanwenden

array([6, 7, 8, 9])

In [51]:
d[d > 5]  # Kurzform

array([6, 7, 8, 9])

In [55]:
x = np.random.randint(100, size=(100))

In [56]:
# Aufgabe: Alle überdurchschnittlichen Werte finden

In [57]:
x

array([90, 54, 21, 57,  1, 86, 46, 43,  8,  5, 34, 51, 31, 88, 98, 75, 33,
       32, 74, 87, 59, 29, 13, 67, 50, 27, 50, 15, 46, 21, 40, 70, 27, 75,
        4, 47,  3, 35, 87, 79, 80, 71, 70, 15, 20, 89, 65,  8,  5, 24, 67,
       37, 39, 68, 14, 94, 53, 71, 12, 10, 12, 88, 58, 60,  8,  5, 82, 74,
       50, 90, 11, 89, 38,  6, 30, 13, 73, 57, 69,  1, 73, 39, 70,  8, 36,
       13, 27, 24, 74, 30, 43, 78, 82, 21, 84, 53,  6, 30, 18, 76],
      dtype=int32)

In [58]:
x.mean()

np.float64(45.69)

In [59]:
x > x.mean()

array([ True,  True, False,  True, False,  True,  True, False, False,
       False, False,  True, False,  True,  True,  True, False, False,
        True,  True,  True, False, False,  True,  True, False,  True,
       False,  True, False, False,  True, False,  True, False,  True,
       False, False,  True,  True,  True,  True,  True, False, False,
        True,  True, False, False, False,  True, False, False,  True,
       False,  True,  True,  True, False, False, False,  True,  True,
        True, False, False,  True,  True,  True,  True, False,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False,  True,  True, False,  True,  True, False, False, False,
        True])

In [63]:
y = x[x > x.mean()]

In [64]:
y.sort()

In [65]:
y

array([46, 46, 47, 50, 50, 50, 51, 53, 53, 54, 57, 57, 58, 59, 60, 65, 67,
       67, 68, 69, 70, 70, 70, 71, 71, 73, 73, 74, 74, 74, 75, 75, 76, 78,
       79, 80, 82, 82, 84, 86, 87, 87, 88, 88, 89, 89, 90, 90, 94, 98],
      dtype=int32)